apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: alice-prod-rb
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alice-prod
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: alice
