apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: alice-prod
  namespace: prod
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  resourceNames:
  - logging-api-token
