apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: default
spec:
  encryptedData:
    foo: AgBZSFBk7AgWQrPysJKoOejR7mU6/5Stgrp3b4kUTJPeQhQ/wkvitYTJroEk5jQxjrggHoKZUdFGx/u6olVrbeO2yongAy5CY3K9GKjh5/82ZKzvVJ3xKZ6SZszJxFVl2+Pe+NzdkmOSFIRbnliu63YKPrIbRlMY9KqxLvZ8/2jQMiX5d6VsLJmcIIcoC/W/cjfddjlbLb9rXhDsLBdYjLywWUlYZkrc9qy79FHxlGHjizV99F1+kU7hVmMKjd5DRP1/WXOVxl77zIDP2VqLmZqBocAypSvYL4iCBVjgGu3vo+nYy7wEKAQ65p6kGGtnik/M78ssFaOZxNr8XlOpvuCYOyKOGkPKWbkSB2pcfHCkfdol44MI51W2wcLiH0Fd15nAV9TrA16SSJW2OYXRndHwkX+h5zV0fFKnvKh63zr1S9pDX5Upv1H7g3dE9tGP/sj1hDSRee0kBq7Xqw9urXYxo0nn5fyHCa2MDf+ondI3D1osS3w+e2HqE9jOABMY6jLZqcZsVpPBu5Nv+4f0fPZ0S8G76SFKz0tnrOFsDli3rYo/cTH87Y0S4wsudI/qw9Av7X2HwVKt1WKyjN3reqLPkVv6uwrUFSuwpzNuf1dZvklSSh6LVHKOS/m2djC3VcDHZDqTinAuS1hUo3fRBnSJK4GP228in5LgnKTHb8GZJOm/khIux3nE449VuFM4SVHfCTQ=
  template:
    metadata:
      creationTimestamp: null
      name: test
      namespace: default

